module.exports = {
    "parser": "",
    "parserOptions": {
        "ecmaVersion": 10,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "plugins": [],
    "env": {
        "es6": true,
        "browser": true,
        "node": true
    },
    "rules": {
        "strict": 2,
        // "no-tabs": [1, { "allowIndentationTabs": true }],
        "no-undef": [2, { "typeof": true }],
        "no-unused-vars": 1,
        "semi": [1, "always"],
        "comma-dangle": [2, "never"],
        "comma-spacing": [2, { "before": false, "after": true }],
        "comma-style": [2, "last"],
        "no-cond-assign": [2, "except-parens"],
        "for-direction": 2,
        "getter-return": 2,
        "no-constant-condition": 2,
        "no-dupe-args": 2,
        "no-dupe-keys": 2,
        "no-duplicate-case": 2,
        "no-dupe-class-members": 2,
        "no-duplicate-imports": 2,
        "no-empty": [2, { "allowEmptyCatch": true }],
        "no-empty-character-class": 2,
        "no-invalid-regexp": 2,
        "no-regex-spaces": 2,
        "no-extra-boolean-cast": 2,
        "no-extra-semi": 2,
        "no-func-assign": 2,
        "no-import-assign": 2,
        "no-irregular-whitespace": [2, {
            "skipStrings": true,
            "skipComments": true,
            "skipRegExps": true,
            "skipTemplates": true
        }],
        "no-sparse-arrays": 2,
        "no-unexpected-multiline": 2,
        "no-unreachable": 2,
        "no-unsafe-finally": 2,
        "no-unsafe-negation": 2,
        "no-this-before-super": 2,
        // "require-atomic-updates": 2,
        "use-isnan": 2,
        "valid-typeof": 2,
        "array-callback-return": [2, { "allowImplicit": true }],
        "array-element-newline": [1, "consistent"],
        "curly": [2, "multi-line", "consistent"],
        "brace-style": [2, "1tbs", { "allowSingleLine": true }],
        "block-spacing": [2, "always"],
        "no-multiple-empty-lines": [1, { "max": 2 }],
        "no-extra-bind": 2,
        "no-unneeded-ternary": 2,
        "operator-assignment": [1, "always"],
        "no-const-assign": 2,
        "no-new-symbol": 2,
        "no-useless-computed-key": 2,
        "object-shorthand": 1,
        "require-yield": 2,
        // "eqeqeq": [1, "smart"],
        "prefer-const": 2,
        "no-trailing-spaces": 1,
        "no-multi-spaces": 2,
        "semi-spacing": [1, { "before": false, "after": true }],
        "object-curly-spacing": [1, "always", { "objectsInObjects": true, "arraysInObjects": true }],
        "array-bracket-spacing": [1, "never", { "objectsInArrays": false, "arraysInArrays": false }],
        "key-spacing": [1, { "beforeColon": false, "afterColon": true, "mode": "strict" }],
        "keyword-spacing": 1,
        "computed-property-spacing": [1, "never"],
        "space-before-blocks": [1, "always"/* { "functions": "never" }*/],
        "space-before-function-paren": [1, { "anonymous": "never", "named": "never", "asyncArrow": "always" }],
        "space-infix-ops": [1, { "int32Hint": false }],
        "space-in-parens": [1, "never"],
        "space-unary-ops": [1, { "words": true, "nonwords": false }],
        "spaced-comment": [1, "always"],
        "switch-colon-spacing": [1, { "after": true, "before": false }],
        "template-tag-spacing": [1, "never"],
        "arrow-spacing": [1, { "before": true, "after": true }],
        "generator-star-spacing": [1, { "before": true, "after": false }],
        "yield-star-spacing": [1, { "before": true, "after": false }],
        "rest-spread-spacing": [1, "never"],
        "template-curly-spacing": [1, "never"],
        "no-mixed-spaces-and-tabs": 1,
        "no-whitespace-before-property": 1,
        "object-curly-newline": [1, { "consistent": true, "multiline": true }],
        "object-property-newline": [1, { "allowAllPropertiesOnSameLine": true }],
        "no-template-curly-in-string": 1,
        "no-unused-expressions": 1,
        "quote-props": [1, "as-needed", { "unnecessary": true }],
        "semi-style": [1, "last"],
        "arrow-body-style": [2, "as-needed"],
        "arrow-parens": [2, "always"],
        "indent": [1, "tab", {
            "SwitchCase": 1,
            "VariableDeclarator": { "var": 2, "let": 2, "const": 3 },
            "MemberExpression": "off",
            "FunctionDeclaration": { "body": 1, "parameters": 2 }
        }],
        "no-console": [2, { "allow": ["warn", "error"] }],
        "operator-linebreak": [2, "after", { "overrides": { "?": "ignore", ":": "ignore" } }],
        "quotes": [2, "single", { "avoidEscape": true }],
        "wrap-iife": [2, "inside", { "functionPrototypeMethods": true }],
        "yoda": 2,
        "padded-blocks": [1, "never"],
        "eol-last": [2, "always"],
        "jsx-quotes": [2, "prefer-single"]
        // maybe
        // "lines-between-class-members": [1, "always"],
        // "prefer-destructuring": ["error", { "array": true, "object": true }]
    }
};
